---
- name: Deploy a configuration snippet on Cisco IOS routers which contains L3VPN service configs
  hosts: ios-routers
  gather_facts: yes

  vars:
  - path_configs: "/vagrant/NetAutomation_materials/Week3-assignments/l3vpn/config"

  tasks:
  - ios_config:
      src:      "{{path_configs}}/{{inventory_hostname}}-service-config.cfg"
      host:     "{{ansible_host}}"
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
    register: ios_results

  - copy:
      content: "{{ios_results}}"
      dest: "{{debug_output}}/{{inventory_hostname}}-deploy-service-config-log-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}.json"
    when: debug_output is defined