---
- name:  Read device data from saved .YML files. Generate text report.
  hosts: ios-switches
  gather_facts: no

  vars:
  - results: results
  - path_report: "{{results}}/{{inventory_hostname}}-if-mac-report.yml"

  tasks:
  - include_vars: "{{results}}/{{inventory_hostname}}-if-info.yml"
  - include_vars: "{{results}}/{{inventory_hostname}}-mac-table.yml"

  - name: Create final report based on loaded variables and Jinja2 template
    template: src=interface-mac-report.j2 dest={{path_report}}