---
- name:  Collect MAC-address tables from IOS Switches. Save them to YAML files
  hosts: ios-switches
  vars:
  - results: results
  tasks:
  - name: Create results directory
    file: path={{results}} state=directory
    run_once: true

  - name: Gather MAC-address table from IOS Switches
    ios_command:
      commands: "show mac address-table"
      provider: "{{ios_provider}}"
    register: result

  - name: Copy results to yaml file in results directory
    copy: content="{{result.stdout}" dest={{results}}/{{inventory_hostname}}.yml
#   copy: content="{{result.stdout|to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.yml
