---
- name:  Collect IOS facts from devices. Save them to YAML files
  hosts: ios
  vars:
  - results: results
  tasks:
  - name: Create results directory
    file: path={{results}} state=directory
    run_once: true

  - name: Gather facts from IOS devices
    ios_facts: provider={{ios_provider}}
    register: result

  - name: Copy results to yaml file in results directory
    copy: content="{{result.ansible_facts|to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.yml
