---
- name:  Reads Low Level Service data-model .YML file and corresponding Jinja2 template and generates MS Visio based network diagram
  hosts: ios-routers
  gather_facts: no

  vars:
  - path_configs: "drawing/diagrams"
  tasks:
  - name: Create directory for results
    file: path={{path_configs}} state=directory
    run_once: true

  - include_vars: "l3vpn/service-datamodel-l3vpn-ll.yml"
    run_once: true

  - template: src="drawing/service-diagram-template-l3vpn.j2" dest={{path_configs}}/{{inventory_hostname}}-diagram.dot
    run_once: true

  - command: dot -T png {{path_configs}}/{{inventory_hostname}}-diagram.dot -o {{path_configs}}/{{inventory_hostname}}-diagram.png
    run_once: true