---
- name:  Reads High Level Service and infrastructure data-model .YML file and corresponding jinja2 template and generates low lewel service data model
  hosts: ios-routers
  gather_facts: no

  vars:
  - path_configs: "l3vpn"



  tasks:
  - name: Create directory for results
    file: path={{path_configs}} state=directory
    run_once: true

  - include_vars: "infra-datamodel-mpls-backbone.yml"
    run_once: true
    
  - include_vars:
      file: "service-datamodel-l3vpn-hl.yml"
      name: l3vpns
    run_once: true

  - template: src="l3vpn/service-hl2ll-template-l3vpn.j2" dest={{path_configs}}/service-datamodel-l3vpn-ll.yml
    run_once: true