---
- hosts: localhost
  gather_facts: no

  tasks:
  - debug:
      msg: "Does this overlap? {{ ['10.0.0.0/24', '10.0.1.0/24'] | net_overlap }}"

  - debug:
      msg: "Does this overlap? {{ ['10.0.0.0/24', '10.0.1.0/24', '10.0.0.128/25'] | net_overlap }}"