# Validate correctness High Level Service Data Model of L3VPN Service
#
---
- hosts: localhost
  name:  Validate Services Data model contents
  gather_facts: no
  vars:
  - services_path: "broken-data-models"

  tasks:

  - include_vars: 
      file: "{{svcs}}"
      name: l3vpns

  - name: 2 - Check wether l3vpns is defined in the Data Model
    assert:
      that: l3vpns is defined
      msg: "l3vpns not defined correctly"

  - name: 3 - Check if l3vpns is dictionary
    assert:
      that: l3vpns.keys() is defined
      msg: "l3vpns is not dictionary"

  - name: 3 - Check if there is more than zero l3vpns defined
    assert:
      that: l3vpns|length >= 1
      msg: "l3vpns has no l3vpns"

  - name: 4 - Check wether l3vpns has connection_to_firewall set to TRUE or FALSE
    assert:
      that: (item.connection_to_firewall == true) or (item.connection_to_firewall == false)
      msg: "l3vpns has no connection_to_firewall defined or value is not TRUE or FALSE" 
    with_items: "{{l3vpns.values()}}"

  - name: 5 - Check wether l3vpns has real number in id field
    assert:
      that: item.id is number
      msg: "l3vpns id is not real number" 
    with_items: "{{l3vpns.values()}}" #}

  - name: 5 - Check if id is unique
    assert:
      that: l3vpns.values()|map(attribute='id')|list|unique|length == l3vpns|length
      msg: "L3vpns ID is not unique"

  - name: 6 - Check if prefix is real IPv4 prefix
    assert:
      that: item.prefix|ipv4 != false
      msg: "Prefix is not valid ipv4 prefix"
    with_items: "{{l3vpns.values()}}"

  - name: 6 - Check if prefix is unique
    assert:
      that: not l3vpns.values()|map(attribute='prefix')|list|net_overlap
      msg: "L3vpns prefixes are not unique"

  - name: 7 - Check if sites is list
    assert:
      that: item.sites is iterable
      msg: "Sites is not list"
    with_items: "{{l3vpns.values()}}"

  - name: 7 - Check if there is more than zero sites defined
    assert:
      that: item.sites|length >= 1
      msg: "sites has no sites defined"
    with_items: "{{l3vpns.values()}}"

  - name: 8 - Check that data model has nothing more defined
    assert:
      that: item.keys()|difference(['connection_to_firewall','prefix','id','sites'])|length == 0
      msg: "Data Model has unknown data in it"
    with_items: "{{l3vpns.values()}}"

